[server]
port = 8080

[log]
level = "info"
path = "./logs"
name = "ethereum-parser"
error_log = "error.log"
warn_log = "warn.log"
info_log = "info.log"
debug_log = "debug.log"
max_size = 300
max_backups = 7
max_age= 7
disable_stacktrace = false

[ethereum]
url = "https://eth-mainnet.g.alchemy.com/v2/TYWdAcIlByMmx_MKEb2HpZ0L3WcgVLBk"

[cron]
url = "https://eth-mainnet.g.alchemy.com/v2/TYWdAcIlByMmx_MKEb2HpZ0L3WcgVLBk"
period = "@every 1s"